<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Waste list</title>
    
    <style>
	td{
		font-size:14px;
	}
	th{
		font-weight:600;
		font-size:14px;
	}
	
    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 10px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }
    
    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
    }
    
    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }
	.invoice-box table th {
        padding: 5px;
        vertical-align: top;
		text-align:center;
		
    }
    

    
    .invoice-box table tr.top table td {
        padding-bottom: 0px;
    }
    
    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }
    
    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }
    
    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        
    }
    
    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }
    
    .invoice-box table tr.item.last td {
        border-bottom: none;
    }
    
    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        
    }
	
    
    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }
        
        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }
    
    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }
    
    .rtl table {
        text-align: right;
    }
    
    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
    
    table {
  border-collapse: collapse;
}

table, th, td {
  border: 1px solid black;
}
.bg-yellow {
    background-color: yellow;
    color: #fff;
}
.bg-red {
    background-color: red;
    color: #fff;
}
.bg-blue{
    background-color: blue;
    color: #fff;
}
.bg-white{
    background-color: white;
    color: #000;
}
.text-center{
	text-align:center;
}

    </style>
</head>

<body>
    <div class="invoice-box">
   	<?php if(isset($waste_list) && count($waste_list)>0){ ?>
		<table cellpadding="0" cellspacing="0" style="border:1px solid #aaa;border-bottom:0px solid #fff;">
            <tr >
					<td colspan="12" style="text-align:center;" >
                  <h4 style="text-decoration:underline">HCF WASTE lIST</h4>
                </td>
            </tr> 
			<tr >
                <th rowspan="3" style="text-align:center; vertical-align: middle" >Sr.no</th>
                <th rowspan="3" style="text-align:center;vertical-align: middle" >Name of the HCF</th>
                <th rowspan="3" style="text-align:center;vertical-align: middle" >Address</th>
                <th colspan="9" rowspan="1" style="font-size:14px;">Details of Bio medical Generated by the HCF (Qty. of BMW in Kg)</th>
            </tr> 
			<tr>
				
				<th rowspan="2">Date</th>
				<td colspan="2" class="bg-yellow text-center">Yellow</td>
				<td colspan="2" class="bg-red text-center">Red</td>
				<td colspan="2" class="bg-white text-center">White</td>
				<td colspan="2" class="bg-blue text-center">Blue</td>
				
			</tr>
			<tr>
				<td>No. of Bags</td>
				<td>Quantity</td>
				<td>No. of Bags</td>
				<td>Quantity</td>
				<td>No. of containers</td>
				<td>Quantity</td>
				<td>No. of Bags</td>
				<td>Quantity</td>
			</tr>
		
			<?php $cnt=1;foreach($waste_list as $list){ ?>
			<tr>
				<td> <?php echo $cnt; ?></td>
				<td> <?php echo htmlentities($list['hospital_name']); ?></td>
				
				<td title="<?php echo htmlentities($list['current_address']); ?>"><?php echo htmlentities($list['current_address']); ?></td>
				<td><?php echo htmlentities($list['date']); ?></td>
				
				<td><?php echo htmlentities($list['infected_waste_qt']); ?></td>
				<td><?php echo htmlentities($list['infected_waste_kg']); ?></td>
				<td><?php echo htmlentities($list['infected_plastics_qt']); ?></td>
				<td><?php echo htmlentities($list['infected_plastics_kg']); ?></td>

				<td><?php echo htmlentities($list['genaral_waste_qt']); ?></td>
				<td><?php echo htmlentities($list['genaral_waste_kg']); ?></td>
				<td><?php echo htmlentities($list['glassware_watse_qt']); ?></td>
				<td><?php echo htmlentities($list['glassware_watse_kg']); ?></td>

			</tr>
			<?php $cnt++;} ?>
			
			
			
        </table>
	<?php } ?>
	
    </div>
</body>
</html>
